import test, { expect } from "@playwright/test";
import { allowedNodeEnvironmentFlags } from "process";
const { default: PageHelper } = require('./UsedFunction');
const helper = new PageHelper();
const webSiteUrl = 'https://stagingiidm.wpengine.com/';
const webStoreUrl = 'https://staging-store.iidm.com/';

test('Header Technologies Links', async ({ page }) => {
    await page.goto(webSiteUrl);
    await expect(page.getByText('Accept All', { exact: true })).toBeVisible();
    await page.getByText('Accept All', { exact: true }).click();
    // Indutsrial Sensors link at Technologies dropdown
    await page.getByRole('link', { name: 'Technologies ' }).hover();
    await page.locator('#menu-item-2166').getByRole('link', { name: 'Industrial Sensors' }).click();
    await expect(page.getByRole('heading', { name: 'Sensors and Vision' })).toBeVisible();
    await expect(page.url()).toContain(webSiteUrl);
    await page.locator("//*[text()='Shop for Industrial Sensors']").click();
    await expect(page.getByRole('heading', { name: 'Industrial Control' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop for Industrial Sensors under $200']").click();
    await expect(page.getByRole('heading', { name: 'Industrial Control' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator('//*[text()="Shop now"]').nth(0).click();
    await expect(page.getByRole('heading', { name: 'Industrial Control' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl);
    await expect(page.getByRole('link', { name: '#E2E-X9C112-R 2M' })).toBeVisible();
    await page.goBack();
    await page.locator('//*[text()="Shop now"]').nth(1).click();
    await expect(page.getByRole('heading', { name: 'Industrial Control' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl);
    await expect(page.getByText('#E2E-X9C112-R 2M Omron The')).toBeVisible();
    await page.goBack();
    await page.locator('//*[text()="Shop now"]').nth(2).click();
    await expect(page.getByRole('heading', { name: 'Industrial Control' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl);
    await expect(page.getByText('#E2E-X9C112-R 2M Omron The')).toBeVisible();
    await page.goBack();
    await page.locator('//*[text()="Shop now"]').nth(3).click();
    await expect(page.getByRole('heading', { name: 'Industrial Control' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl);
    await expect(page.getByText('#E2E-X9C112-R 2M Omron The')).toBeVisible();
    await page.goBack();
    await page.locator('//*[text()="Shop now"]').nth(4).click();
    await expect(page.getByRole('heading', { name: 'Industrial Control' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl);
    await expect(page.getByText('#E2E-X9C112-R 2M Omron The')).toBeVisible();
    await page.goBack();
    await page.locator('//*[text()="Shop now"]').nth(5).click();
    await expect(page.getByRole('heading', { name: 'Industrial Control' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl);
    await expect(page.getByText('#E2E-X9C112-R 2M Omron The')).toBeVisible();
    await page.goBack();
    await page.locator("//*[text()='Explore all posts']").scrollIntoViewIfNeeded();
    await expect(page.locator("//*[text()='Explore all posts']")).toBeVisible();
    await page.goBack();
    //Motion Control Technology link at Technology dropdown
    await page.getByRole('link', { name: 'Technologies ' }).hover();
    await page.locator('#menu-item-2204').getByRole('link', { name: 'Motion Control Technology' }).click();
    await expect(page.getByRole('heading', { name: 'Motion control technology' })).toBeVisible();
    await expect(page.url()).toContain(webSiteUrl);
    await page.locator("//*[text()='Shop now']").nth(0).click();
    await expect(page.locator("(//*[text()='Yaskawa'])[2]")).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(1).click();
    await expect(page.locator("(//*[text()='Yaskawa'])[2]")).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(2).click();
    await expect(page.locator("(//*[text()='Yaskawa'])[2]")).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(3).click();
    await expect(page.locator("//*[text()='Add Products']").nth(0)).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Explore all posts']").scrollIntoViewIfNeeded();
    await expect(page.locator("//*[text()='Explore all posts']")).toBeVisible();
    await page.goBack();
    //Industrial Robotics link at Technologies drodpwon
    await page.getByRole('link', { name: 'Technologies ' }).hover();
    await page.locator('#menu-item-2363').getByRole('link', { name: 'Industrial Robotics' }).click();
    await page.getByRole('heading', { name: 'Four Scenarios for Cobots' }).scrollIntoViewIfNeeded();
    await expect(page.getByRole('heading', { name: 'Four Scenarios for Cobots' })).toBeVisible();
    await expect(page.url()).toContain(webSiteUrl);
    await page.locator("//*[text()='Explore all posts']").scrollIntoViewIfNeeded();
    await expect(page.locator("//*[text()='Explore all posts']")).toBeVisible();
    await page.goBack();
    // Variable Frequency Drives link at Technologies drodpwon
    await page.getByRole('link', { name: 'Technologies ' }).hover();
    await page.locator('#menu-item-2394').getByRole('link', { name: 'Variable Frequency Drives' }).click();
    await expect(page.getByText('What is an AC Variable')).toBeVisible();
    await expect(page.url()).toContain(webSiteUrl);
    await expect(page.getByRole('heading', { name: 'Featured VFD Products' })).toBeVisible();
    await page.locator("//*[text()='Shop for Electric motors']").click();
    await expect(page.getByRole('heading', { name: 'Search -' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop for new VFDs']").click();
    await expect(page.getByRole('heading', { name: 'Search -' })).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Repair your existing VFDs']").click();
    await expect(page.locator("//*[text()='Request for Repair']")).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop for Yaskawa VFDs']").click();
    await expect(page.locator("//*[text()='Yaskawa']").nth(1)).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop for ABB VFDs']").click();
    await expect(page.locator("//*[text()='ABB']").nth(1)).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Explore all posts']").scrollIntoViewIfNeeded();
    await expect(page.locator("//*[text()='Explore all posts']")).toBeVisible();
    await page.goBack();
    // Machine Safety link at Technologies dropdown
    await page.getByRole('link', { name: 'Technologies ' }).hover();
    await page.locator('#menu-item-2194').getByRole('link', { name: 'Machine Safety' }).click();
    await expect(page.getByRole('heading', { name: 'Machine and Facility Safety' })).toBeVisible();
    await expect(page.url()).toContain(webSiteUrl);
    await page.locator("//*[text()='Shop for Omron Safety products']").click();
    await expect(page.locator("//*[text()='Safety & Signaling']")).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(0).click();
    await expect(page.locator("//*[text()='Safety & Signaling']")).toBeVisible();
    await expect(page.locator("(//*[@class='mz-filter-group-content more'])[4]/div[1]/div/input")).toBeChecked();
    await helper.categoryFilters(page);
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(1).click();
    await expect(page.locator("//*[text()='Safety & Signaling']")).toBeVisible();
    await expect(page.locator("(//*[@class='mz-filter-group-content more'])[4]/div[2]/div/input")).toBeChecked();
    await helper.categoryFilters(page);
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(2).click();
    await expect(page.locator("//*[text()='Safety & Signaling']")).toBeVisible();
    await expect(page.locator("(//*[@class='mz-filter-group-content more'])[4]/div[3]/div/input")).toBeChecked();
    await helper.categoryFilters(page);
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(3).click();
    await expect(page.locator("//*[text()='Safety & Signaling']")).toBeVisible();
    await expect(page.locator("(//*[@class='mz-filter-group-content more'])[4]/div[4]/div/input")).toBeChecked();
    await helper.categoryFilters(page);
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Explore all posts']").scrollIntoViewIfNeeded();
    await expect(page.locator("//*[text()='Explore all posts']")).toBeVisible();
    await page.goBack();
    // PLC Technology link at Technologies dropdown
    await page.getByRole('link', { name: 'Technologies ' }).hover();
    await page.locator('#menu-item-2364').getByRole('link', { name: 'PLC Technology' }).click();
    await expect(page.getByRole('heading', { name: 'How PLCs revolutionized the' })).toBeVisible();
    await expect(page.url()).toContain(webSiteUrl);
    await page.locator("//*[text()='Omron Automation Systems']").click();
    await expect(page.locator("//*[text()='Omron']").nth(1)).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(0).click();
    await expect(page.locator("//*[text()='Industrial Control']")).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(1).click();
    await expect(page.locator("//*[text()='Industrial Control']")).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(2).click();
    await expect(page.locator("//*[text()='Industrial Control']")).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Explore all posts']").scrollIntoViewIfNeeded();
    await expect(page.locator("//*[text()='Explore all posts']")).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Featured Omron Automation' })).toBeVisible();
    await page.goBack();
    //Pneumatics link at Technologies dropdown
    await page.getByRole('link', { name: 'Technologies ' }).hover();
    await page.locator('#menu-item-2393').getByRole('link', { name: 'Pneumatics' }).click();
    await expect(page.getByRole('heading', { name: 'How pneumatics are used' })).toBeVisible();
    await expect(page.url()).toContain(webSiteUrl);
    await page.locator("//*[text()='Shop now']").nth(0).click();
    await expect(page.locator("//*[text()='Actuators']").nth(1)).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(1).click();
    await expect(page.locator("//*[text()='Chillers']").nth(0)).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(2).click();
    await expect(page.locator("//*[text()='Airline Equipment']").nth(1)).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Shop now']").nth(3).click();
    await expect(page.locator("//*[text()='Connectors']").nth(0)).toBeVisible();
    await expect(page.url()).toContain(webStoreUrl); await page.goBack();
    await page.locator("//*[text()='Explore all posts']").scrollIntoViewIfNeeded();
    await expect(page.locator("//*[text()='Explore all posts']")).toBeVisible();
    await page.goBack();
    await page.getByRole('link', { name: 'Technologies ' }).hover();
    await page.getByRole('link', { name: 'Let us know' }).click();
    await expect(page.getByPlaceholder('Your Name')).toBeVisible();
    await expect(page.url()).toContain(webSiteUrl);
    await expect(page.getByPlaceholder('Your Company Name')).toBeVisible();
    await expect(page.getByPlaceholder('Your Phone number')).toBeVisible();
    await expect(page.getByPlaceholder('Your Email')).toBeVisible();
    await expect(page.getByPlaceholder('Your Message')).toBeVisible();
})